development:
  sessions:
    default:
      database: risks_development
      hosts:
        - localhost:<%= ENV['BOXEN_MONGODB_PORT'] || 27017 %>
staging:
  sessions:
    default:
      database: risks
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: risks
      hosts:
        - localhost:27017